export const tasks =[
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 1","location":"P1 01 01","complete":86},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 01","complete":39},
{"taskName":"Install SVP / RWP","plot":"Plot 1","level":"Level 1","location":"P1 01 01","complete":78},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 1","location":"P1 01 02","complete":43},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 02","complete":45},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 1","location":"P1 01 03","complete":67},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 03","complete":50},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 1","location":"P1 01 04","complete":21},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 04","complete":62},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 1","location":"P1 01 05","complete":46},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 05","complete":76},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 1","location":"P1 01 06","complete":12},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 2","location":"P1 02 01","complete":12},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 01","complete":81},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 2","location":"P1 02 02","complete":88},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 02","complete":63},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 2","location":"P1 02 03","complete":48},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 03","complete":14},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 04","complete":27},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 05","complete":39},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 1","level":"Level 2","location":"P1 02 06","complete":78},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 3","location":"P1 03 01","complete":6},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 3","location":"P1 03 02","complete":63},
{"taskName":"Apartment Partitioning","plot":"Plot 1","level":"Level 3","location":"P1 03 03","complete":39},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 01","complete":56},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 02","complete":33},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 03","complete":33},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 04","complete":48},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 05","complete":91},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 1","location":"P2 01 06","complete":52},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 01","complete":13},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 02","complete":8},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 03","complete":75},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 04","complete":59},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 05","complete":42},
{"taskName":"Commence Stage 1 Fit Out","plot":"Plot 2","level":"Level 2","location":"P2 02 06","complete":16}
];
